version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: accshop
    environment:
      POSTGRES_USER: maiviet283
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: accshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
